---
- name: Install the GNOME Desktop Icons extension
  apt:
    name: gnome-shell-extension-desktop-icons-ng
    state: present
  notify:
    - restart display-manager
  become: yes

- name: Ensure the ~/Desktop directory exists
  file:
    path: ~/Desktop
    state: directory
    mode: 0755

- name: Create the README file on the Desktop
  copy:
    src: README.md
    dest: ~/Desktop/README.md
    mode: 0644
