---
- name: Install the GNOME Desktop Icons extension
  apt:
    name: gnome-shell-extension-desktop-icons
    state: present
  register: gnome_shell_extension_installed

- name: Restart display manager when GNOME shell extension has been installed
  systemd:
    name: display-manager
    state: restarted
  when: gnome_shell_extension_installed.changed

- name: Ensure the ~/Desktop directory exists
  file:
    path: ~/Desktop
    state: directory
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Create the README file on the Desktop
  copy:
    src: README.md
    dest: ~/Desktop/README.md
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"
