---
- name: Install the GNOME Desktop Icons extension
  apt:
    name: gnome-shell-extension-desktop-icons
    state: present

- name: Ensure the ~/Desktop directory exists
  file:
    path: ~/Desktop
    state: directory
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Create the README file on the Desktop
  copy:
    src: README.md
    dest: ~/Desktop/README.md
  become_user: "{{ ansible_env.SUDO_USER }}"
