---
- name: Update apt cache
  hosts: localhost
  tasks:
    - name: Update apt cache before running any of the ansible roles
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

- name: Install toolchain
  hosts: localhost
  roles:
    - { role: readme, tags: readme }
    - { role: ansible-lint, tags: ansible-lint }
    - { role: testinfra, tags: testinfra }
    - { role: bashrc_d, tags: bashrc_d }
    - { role: docker-hacks, tags: docker-hacks, when: ansible_virtualization_type == "docker" }
    - { role: cache, tags: cache }
    - { role: git, tags: git }
    - { role: vscode, tags: vscode }
    - { role: docker, tags: docker }
