---
- name: Update apt cache
  hosts: localhost
  tasks:
    - name: Update apt cache before running any of the ansible roles
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

- name: Install toolchain
  hosts: localhost
  roles:
    - { role: base-toolchain, tags: "base" }