---

- hosts: localhost
  tasks:
    - name: update apt cache before running any of the ansible roles
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: localhost
  roles:
    - { role: readme, tags: "readme" }
