---

- hosts: localhost
  tasks:
    - name: update apt cache before running any of the ansible roles
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: localhost
  roles:
    - { role: readme, tags: "readme" }
    - { role: ansible-lint, tags: "ansible-lint" }
    - { role: testinfra, tags: "testinfra" }
    - { role: bashrc_d, tags: "bashrc_d" }
    - { role: git, tags: "git" }
    - { role: vscode, tags: "vscode" }
