---

- name: Add VSCode apt signing key if not present
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Microsoft's VSCode repository into sources list
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Install VSCode
  apt:
    name: code
    state: present
