---

- name: Install VSCode version 1.57.1 from .deb package
  apt:
    deb: https://update.code.visualstudio.com/1.57.1/linux-deb-x64/stable
    state: present

- name: List VSCode Extensions
  command:
    cmd: code --list-extensions
  register: vscode_installed_extensions
  changed_when: false
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"

- name: Install VSCode Extensions
  command:
    cmd: code --install-extension "{{ item }}"
  with_items: "{{ vscode_extensions }}"
  when: not vscode_installed_extensions is search(item)
  become: yes
  become_user: "{{ ansible_env.SUDO_USER }}"
