version: 2.1

executors:
  linux_amd64:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
  macos_arm64:
    macos:
      xcode: 15.0.0
    resource_class: macos.m1.medium.gen1

jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    environment:
      VAGRANT_DEFAULT_PROVIDER: docker
    steps:
      - checkout
      - run:
          name: Install Vagrant
          command: |
            wget https://releases.hashicorp.com/vagrant/2.4.0/vagrant_2.4.0-1_amd64.deb
            sudo dpkg -i vagrant_2.4.0-1_amd64.deb
      - run:
          name: Bring up Developer VM
          command: vagrant up --no-provision
      - run:
          name: Provision Developer VM
          command: UPDATE_VM_FLAGS=--provision-only vagrant provision
      - run:
          name: Test Developer VM
          command: UPDATE_VM_FLAGS=--verify-only vagrant provision
      - run:
          name: Export Test Results
          command: |
            mkdir -p test-results/junit
            vagrant ssh -c 'sudo ls -la /home/user/vm-setup/out/'
            vagrant ssh -c 'sudo cat /home/user/vm-setup/out/report.xml' > test-results/junit/junit-report.xml
            vagrant ssh -c 'sudo cat /home/user/vm-setup/out/report.html' > test-results/test-report.html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  all-builds:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux_amd64, macos_arm64]