version: 2.1

jobs:
  build:
    parameters:
      target_platform:
        type: string
    machine:
      image: ubuntu-2004:current
    resource_class: large
    environment:
      VAGRANT_DEFAULT_PROVIDER: docker
      DOCKER_DEFAULT_PLATFORM: << parameters.target_platform >>
    steps:
      - checkout
      - run:
          name: Install Vagrant
          command: |
            wget https://releases.hashicorp.com/vagrant/2.4.0/vagrant_2.4.0-1_amd64.deb
            sudo dpkg -i vagrant_2.4.0-1_amd64.deb
      - run:
          name: Install QEMU
          command: sudo apt update && sudo apt install qemu-user-static -y
      - run:
          name: Bring up Developer VM
          command: vagrant up --no-provision
      - run:
          name: Provision Developer VM
          command: UPDATE_VM_FLAGS=--provision-only vagrant provision
      - run:
          name: Test Developer VM
          command: UPDATE_VM_FLAGS=--verify-only vagrant provision
      - run:
          name: Export Test Results
          command: |
            mkdir -p test-results/junit
            vagrant ssh -c 'sudo ls -la /home/user/vm-setup/out/'
            vagrant ssh -c 'sudo cat /home/user/vm-setup/out/report.xml' > test-results/junit/junit-report.xml
            vagrant ssh -c 'sudo cat /home/user/vm-setup/out/report.html' > test-results/test-report.html
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  all-builds:
    jobs:
      - build:
          matrix:
            parameters:
              target_platform:
                - linux/amd64
                - linux/arm64
