---
- name: Install the GNOME Desktop Icons extension
  ansible.builtin.apt:
    name: gnome-shell-extension-desktop-icons-ng
    state: present
  notify:
    - Restart display-manager
  become: true

- name: Ensure the ~/Desktop directory exists
  ansible.builtin.file:
    path: ~/Desktop
    state: directory
    mode: "0755"

- name: Create the README file on the Desktop
  ansible.builtin.copy:
    src: README.md
    dest: ~/Desktop/README.md
    mode: "0644"
