---
# note: this mimics systemd, allowing to start systemd services in container which would otherwise not work
# source: https://github.com/gdraheim/docker-systemctl-replacement at 9cbe1a00eb4bdac6ff05b96ca34ec9ed3d8fc06c
- name: Inject docker systemctl replacement (required for testing in container only)
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/036f3e49f85689b1fe1ec2e776d4814110645864/files/docker/systemctl3.py
    dest: /usr/bin/systemctl
    mode: "0755"
    checksum: sha256:eb0764a6eff4641c478f55a4d4ffe1725059d8cdcbd57f8752fff2c1060e977e
  become: true
- name: Ensure systemd run directory exists
  ansible.builtin.file:
    path: /run/systemd/system/
    state: directory
    mode: "0755"
  become: true

# note: this allows to start GUI applications in the container but using the host's DISPLAY
- name: Forward DISPLAY variable to the docker host
  ansible.builtin.copy:
    content: |
      # forward the X11 DISPLAY to the docker host
      export DISPLAY=host.docker.internal:0
    dest: ~/.bashrc.d/x11-display.bash
    mode: "0644"

# note: we can use this to skip problematic parts when running under qemu emulation
- name: Set fact whether we are running under QEMU emulation or not
  ansible.builtin.set_fact:
    running_under_qemu_emulation: "{{ ansible_architecture == 'aarch64' and ansible_processor[1] == 'GenuineIntel' }}"
- name: Place marker file when running under QEMU emulation
  ansible.builtin.file:
    path: /.qemu_emulation
    state: "{{ 'touch' if running_under_qemu_emulation else 'absent' }}"
    mode: "0644"
  become: true
