---
- name: Make sure Git is installed
  ansible.builtin.apt:
    name: git
    state: present
  become: true

- name: Set up the PS1 shell prompt for Git
  ansible.builtin.copy:
    src: git-ps1.bash
    dest: ~/.bashrc.d/git-ps1.bash
    mode: "0644"

- name: Supply default configuration entries in ~/.gitconfig
  community.general.git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  with_dict:
    # basic settings
    core.autocrlf: input
    pull.rebase: "true"
    # useful aliases
    alias.co: checkout
    alias.ci: commit
    alias.br: branch
    alias.st: status
    alias.unstage: reset HEAD --
    alias.slog: log --pretty=oneline --abbrev-commit
    alias.graph: log --all --oneline --graph --decorate
    alias.stash-all: stash save --include-untracked
    alias.prune: fetch --prune
