---

- name: Install Containerd 1.4.6
  apt:
    deb: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/containerd.io_1.4.6-1_amd64.deb
    state: present

- name: Install Docker CE CLI 20.10.7
  apt:
    deb: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce-cli_20.10.7~3-0~ubuntu-focal_amd64.deb
    state: present

- name: Install Docker CE Engine 20.10.7
  apt:
    deb: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/docker-ce_20.10.7~3-0~ubuntu-focal_amd64.deb
    state: present
