---

- name: Download Docker CE .deb Packages
  get_url:
    url: https://download.docker.com/linux/ubuntu/dists/focal/pool/stable/amd64/{{ item.deb_file }}
    checksum: "sha256:{{ item.sha256sum }}"
    dest: "{{ download_cache_dir }}/{{ item.deb_file }}"
    force: no
  with_items: "{{ docker_deb_packages }}"

- name: Install Docker CE .deb Packages
  apt:
    deb: "{{ download_cache_dir }}/{{ item.deb_file }}"
    state: present
  with_items: "{{ docker_deb_packages }}"
  become: yes

- name: Add VM user to 'docker' group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes

- name: Ensure containerd service is started and enabled
  service:
    name: containerd
    state: started
    enabled: yes
  become: yes

- name: Ensure the /etc/systemd/system/docker.service.d override directory exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  become: yes

- name: Override docker service configuration (omit '-H fd://' in ExecStart)
  copy:
    content: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd --containerd=/run/containerd/containerd.sock
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: 0644
  become: yes

- name: Ensure docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes
  become: yes