---

- name: Install testinfra at version 6.3.0
  pip:
    name: pytest-testinfra
    version: 6.3.0
    state: present
  become: yes

- name: Install pytest-spec formatter at version 3.2.0
  pip:
    name: pytest-spec
    version: 3.2.0
    state: present
  become: yes

- name: Install pytest-html reporter at version 3.1.1
  pip:
    name: pytest-html
    version: 3.1.1
    state: present
  become: yes